[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"
  
  # Node version - updated to 20 for React Router 7.6.0 compatibility
  environment = { NODE_VERSION = "20" }

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # HTTPS redirect
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    
    # Content security (adjust if needed for your APIs)
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://mainnet.base.org https://api.pinata.cloud https://gateway.pinata.cloud https://*.thirdweb.com wss://*.thirdweb.com; img-src 'self' https://gateway.pinata.cloud https://*.pinata.cloud data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:;"
    
    # XSS protection
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"